[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "rcs_robotiq2f85"
version = "0.7.2"
description="RCS RobotiQ module"
dependencies = [
    "rcs-core>=0.7.2",
    "robotiq2f==0.2.0",
]
readme = "README.md"
maintainers = [
  { name = "Tobias Juelg", email = "tobias.juelg@utn.de" },
]
authors = [
  { name = "Tobias Juelg", email = "tobias.juelg@utn.de" },
]
requires-python = ">=3.11"
license = "AGPL-3.0-or-later"
